[2024-02-28 09:30:38,950] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: email_teste.send_email 2024-02-28T09:30:11.902138+00:00 [queued]>
[2024-02-28 09:30:38,980] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: email_teste.send_email 2024-02-28T09:30:11.902138+00:00 [queued]>
[2024-02-28 09:30:38,981] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2024-02-28 09:30:38,981] {taskinstance.py:1096} INFO - Starting attempt 1 of 2
[2024-02-28 09:30:38,981] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2024-02-28 09:30:39,012] {taskinstance.py:1115} INFO - Executing <Task(EmailOperator): send_email> on 2024-02-28T09:30:11.902138+00:00
[2024-02-28 09:30:39,022] {standard_task_runner.py:52} INFO - Started process 96 to run task
[2024-02-28 09:30:39,028] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'email_teste', 'send_email', '2024-02-28T09:30:11.902138+00:00', '--job-id', '173', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/email.py', '--cfg-path', '/tmp/tmpkli2m2em', '--error-file', '/tmp/tmpu7v3jcbj']
[2024-02-28 09:30:39,029] {standard_task_runner.py:77} INFO - Job 173: Subtask send_email
[2024-02-28 09:30:39,132] {logging_mixin.py:109} INFO - Running <TaskInstance: email_teste.send_email 2024-02-28T09:30:11.902138+00:00 [running]> on host 7e4a9fdea90d
[2024-02-28 09:30:39,246] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=jezandre_tiago@hotmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=email_teste
AIRFLOW_CTX_TASK_ID=send_email
AIRFLOW_CTX_EXECUTION_DATE=2024-02-28T09:30:11.902138+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-28T09:30:11.902138+00:00
[2024-02-28 09:30:39,283] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/email.py:102 PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2024-02-28 09:30:39,284] {email.py:208} INFO - Email alerting: attempt 1
[2024-02-28 09:30:43,553] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/email.py", line 88, in execute
    conn_id=self.conn_id,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/email.py", line 66, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/email.py", line 102, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/email.py", line 219, in send_mime_email
    conn.login(smtp_user, smtp_password)
  File "/usr/local/lib/python3.6/smtplib.py", line 735, in login
    raise last_exception
  File "/usr/local/lib/python3.6/smtplib.py", line 726, in login
    initial_response_ok=initial_response_ok)
  File "/usr/local/lib/python3.6/smtplib.py", line 647, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.9 Application-specific password required. For more information, go to\n5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor s188-20020a625ec5000000b006e46672df97sm7699095pfb.75 - gsmtp')
[2024-02-28 09:30:43,569] {taskinstance.py:1513} INFO - Marking task as UP_FOR_RETRY. dag_id=email_teste, task_id=send_email, execution_date=20240228T093011, start_date=20240228T093038, end_date=20240228T093043
[2024-02-28 09:30:43,684] {local_task_job.py:151} INFO - Task exited with return code 1
[2024-02-28 09:30:43,742] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
