[2024-02-27 08:41:35,660] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: triggerDag3.tsk1 2024-02-27T08:41:34.782410+00:00 [queued]>
[2024-02-27 08:41:35,690] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: triggerDag3.tsk1 2024-02-27T08:41:34.782410+00:00 [queued]>
[2024-02-27 08:41:35,691] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2024-02-27 08:41:35,691] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2024-02-27 08:41:35,691] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2024-02-27 08:41:35,708] {taskinstance.py:1115} INFO - Executing <Task(BashOperator): tsk1> on 2024-02-27T08:41:34.782410+00:00
[2024-02-27 08:41:35,720] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'triggerDag3', 'tsk1', '2024-02-27T08:41:34.782410+00:00', '--job-id', '33', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/triggerDag3.py', '--cfg-path', '/tmp/tmp77h89ra7', '--error-file', '/tmp/tmpyo9nxp32']
[2024-02-27 08:41:35,715] {standard_task_runner.py:52} INFO - Started process 77 to run task
[2024-02-27 08:41:35,721] {standard_task_runner.py:77} INFO - Job 33: Subtask tsk1
[2024-02-27 08:41:35,786] {logging_mixin.py:109} INFO - Running <TaskInstance: triggerDag3.tsk1 2024-02-27T08:41:34.782410+00:00 [running]> on host 1034e60698e1
[2024-02-27 08:41:35,870] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerDag3
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-02-27T08:41:34.782410+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-27T08:41:34.782410+00:00
[2024-02-27 08:41:35,871] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-02-27 08:41:35,872] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'exit 1']
[2024-02-27 08:41:35,884] {subprocess.py:74} INFO - Output:
[2024-02-27 08:41:35,886] {subprocess.py:82} INFO - Command exited with return code 1
[2024-02-27 08:41:35,905] {taskinstance.py:1463} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1165, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1283, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1313, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2024-02-27 08:41:35,908] {taskinstance.py:1513} INFO - Marking task as FAILED. dag_id=triggerDag3, task_id=tsk1, execution_date=20240227T084134, start_date=20240227T084135, end_date=20240227T084135
[2024-02-27 08:41:35,976] {local_task_job.py:151} INFO - Task exited with return code 1
[2024-02-27 08:41:36,016] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
