[2024-03-05T09:53:07.242+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: hook.select_data_task manual__2024-03-05T09:52:58.375909+00:00 [queued]>
[2024-03-05T09:53:07.273+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: hook.select_data_task manual__2024-03-05T09:52:58.375909+00:00 [queued]>
[2024-03-05T09:53:07.274+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-03-05T09:53:07.274+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-03-05T09:53:07.274+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-03-05T09:53:07.313+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): select_data_task> on 2024-03-05 09:52:58.375909+00:00
[2024-03-05T09:53:07.325+0000] {standard_task_runner.py:55} INFO - Started process 141 to run task
[2024-03-05T09:53:07.330+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'hook', 'select_data_task', 'manual__2024-03-05T09:52:58.375909+00:00', '--job-id', '318', '--raw', '--subdir', 'DAGS_FOLDER/hooks.py', '--cfg-path', '/tmp/tmpu8lr8tbq']
[2024-03-05T09:53:07.331+0000] {standard_task_runner.py:83} INFO - Job 318: Subtask select_data_task
[2024-03-05T09:53:07.359+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-03-05T09:53:07.495+0000] {task_command.py:388} INFO - Running <TaskInstance: hook.select_data_task manual__2024-03-05T09:52:58.375909+00:00 [running]> on host df7038a2f7dd
[2024-03-05T09:53:07.771+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hook
AIRFLOW_CTX_TASK_ID=select_data_task
AIRFLOW_CTX_EXECUTION_DATE=2024-03-05T09:52:58.375909+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-05T09:52:58.375909+00:00
[2024-03-05T09:53:07.774+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/hooks.py", line 21, in select_data
    records = pg_hook.get_records('select * from teste2;', autocommit=True)
TypeError: get_records() got an unexpected keyword argument 'autocommit'
[2024-03-05T09:53:07.811+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=hook, task_id=select_data_task, execution_date=20240305T095258, start_date=20240305T095307, end_date=20240305T095307
[2024-03-05T09:53:07.871+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 318 for task select_data_task (get_records() got an unexpected keyword argument 'autocommit'; 141)
[2024-03-05T09:53:07.917+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-03-05T09:53:08.075+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
