[2024-03-05T09:51:29.428+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: hook.print_data_task manual__2024-03-05T09:51:22.719642+00:00 [queued]>
[2024-03-05T09:51:29.447+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: hook.print_data_task manual__2024-03-05T09:51:22.719642+00:00 [queued]>
[2024-03-05T09:51:29.447+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-03-05T09:51:29.447+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-03-05T09:51:29.447+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-03-05T09:51:29.474+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): print_data_task> on 2024-03-05 09:51:22.719642+00:00
[2024-03-05T09:51:29.482+0000] {standard_task_runner.py:55} INFO - Started process 135 to run task
[2024-03-05T09:51:29.486+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'hook', 'print_data_task', 'manual__2024-03-05T09:51:22.719642+00:00', '--job-id', '315', '--raw', '--subdir', 'DAGS_FOLDER/hooks.py', '--cfg-path', '/tmp/tmp4f1mdh4q']
[2024-03-05T09:51:29.487+0000] {standard_task_runner.py:83} INFO - Job 315: Subtask print_data_task
[2024-03-05T09:51:29.504+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-03-05T09:51:29.595+0000] {task_command.py:388} INFO - Running <TaskInstance: hook.print_data_task manual__2024-03-05T09:51:22.719642+00:00 [running]> on host df7038a2f7dd
[2024-03-05T09:51:29.755+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hook
AIRFLOW_CTX_TASK_ID=print_data_task
AIRFLOW_CTX_EXECUTION_DATE=2024-03-05T09:51:22.719642+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-03-05T09:51:22.719642+00:00
[2024-03-05T09:51:29.777+0000] {logging_mixin.py:137} INFO - Dados da tabela:
[2024-03-05T09:51:29.777+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/hooks.py", line 27, in print_data
    for row in task_instance:
TypeError: 'NoneType' object is not iterable
[2024-03-05T09:51:29.791+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=hook, task_id=print_data_task, execution_date=20240305T095122, start_date=20240305T095129, end_date=20240305T095129
[2024-03-05T09:51:29.810+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 315 for task print_data_task ('NoneType' object is not iterable; 135)
[2024-03-05T09:51:29.818+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-03-05T09:51:29.846+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
